# Generated by Django 2.2.7 on 2020-01-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('comments', models.TextField(max_length=200)),
                ('total_time', models.IntegerField()),
            ],
        ),
    ]
