# Generated by Django 3.0 on 2020-01-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0002_entry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='total_time',
            field=models.FloatField(),
        ),
    ]
