# Generated by Django 3.0 on 2020-01-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expense_cell',
            field=models.BooleanField(default=None),
        ),
    ]
