# Generated by Django 3.0 on 2020-01-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_expense_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expense_cell',
            field=models.BooleanField(default=False),
        ),
    ]
