# Generated by Django 3.0 on 2020-01-16 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('street_address', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('state', models.CharField(default=None, max_length=50)),
                ('contact_name', models.CharField(default=None, max_length=50)),
                ('area_code', models.IntegerField(default=None)),
                ('prefix', models.IntegerField(default=None)),
                ('line_number', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('street_address', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('state', models.CharField(default=None, max_length=50)),
                ('contact_name', models.CharField(default=None, max_length=50)),
                ('area_code', models.IntegerField(default=None)),
                ('prefix', models.IntegerField(default=None)),
                ('line_number', models.IntegerField(default=None)),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notes.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('body', models.TextField(max_length=200)),
                ('site', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notes.Site')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
