# Generated by Django 3.0 on 2020-01-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='area_code',
            field=models.SmallIntegerField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='organization',
            name='line_number',
            field=models.IntegerField(default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name='organization',
            name='prefix',
            field=models.IntegerField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='site',
            name='area_code',
            field=models.IntegerField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='site',
            name='line_number',
            field=models.IntegerField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='site',
            name='prefix',
            field=models.IntegerField(default=None, max_length=4),
        ),
    ]
