# Generated by Django 3.0 on 2020-01-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200116_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='zip_code',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='site',
            name='zip_code',
            field=models.SmallIntegerField(default=None),
        ),
    ]
