# Generated by Django 3.0 on 2020-01-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200116_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='zip_code',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='site',
            name='zip_code',
            field=models.IntegerField(default=None),
        ),
    ]
