# Generated by Django 3.0.2 on 2020-03-02 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_list', models.FileField(upload_to='walktest/')),
                ('test_history', models.FileField(upload_to='walktest/')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Site')),
            ],
        ),
    ]
