# Generated by Django 2.2.7 on 2020-03-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walktest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walktest',
            name='site',
        ),
    ]
