# Generated by Django 3.0.2 on 2020-03-04 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('walktest', '0003_walktest_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walktest',
            name='site',
            field=models.ForeignKey(choices=[('John Martin Housing', 'John Martin Housing'), ('Main St. Dump', 'Main St. Dump'), ('GreenMeadow', 'GreenMeadow')], on_delete=django.db.models.deletion.CASCADE, to='notes.Site'),
        ),
    ]
