# Generated by Django 3.0.2 on 2020-03-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walktest', '0004_auto_20200304_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walktest',
            name='site',
            field=models.CharField(choices=[('John Martin Housing', 'John Martin Housing'), ('Main St. Dump', 'Main St. Dump'), ('GreenMeadow', 'GreenMeadow')], max_length=200),
        ),
    ]
