# Generated by Django 3.0.2 on 2020-03-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walktest', '0005_auto_20200304_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='walktest',
            name='panel',
            field=models.CharField(choices=[('320', '320'), ('640', '640'), ('3030', '3030')], default=320, max_length=200),
            preserve_default=False,
        ),
    ]
