# Generated by Django 3.0.2 on 2020-03-07 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('walktest', '0006_walktest_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='walktest',
            name='site_name',
            field=models.CharField(choices=[('John Martin Housing', 'John Martin Housing'), ('Main St. Dump', 'Main St. Dump'), ('GreenMeadow', 'GreenMeadow'), ('home', 'home')], default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='walktest',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notes.Site'),
        ),
    ]
