# Generated by Django 3.0.2 on 2020-03-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walktest', '0008_walktest_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walktest',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
