# Generated by Django 2.2.2 on 2019-09-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('panel_type', models.CharField(choices=[('320', '320'), ('640', '640'), ('2-3030', '2-3030')], default=None, max_length=100)),
                ('test_date', models.DateTimeField(auto_now=True)),
                ('device_list', models.FileField(default=None, upload_to='')),
                ('alarm_history', models.FileField(default=None, upload_to='')),
                ('test_results', models.FileField(default=None, null=True, upload_to='')),
            ],
        ),
    ]
